networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.30.0/24

services:
  vector:
    image: timberio/vector:0.43.0-debian
    container_name: concentrador-vector
    restart: unless-stopped
    user: "${UID:-0}:${GID:-0}"
    ports:
      - "5044:5044"
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml:ro
      - ./data/logs:/mnt/logs
    command: ["--config", "/etc/vector/vector.yaml"]
