---
- name: Instalar pacotes base
  dnf:
    name:
      - tar
      - gzip
      - findutils
    state: present

- name: Criar grupo de sistema
  group:
    name: "{{ vector_system_group }}"
    system: true
    state: present

- name: Criar usuário de sistema
  user:
    name: "{{ vector_system_user }}"
    group: "{{ vector_system_group }}"
    system: true
    shell: /sbin/nologin
    create_home: false
    state: present
