filebeat.inputs:
  - type: log
    paths:
      - /var/log/app/shipping-app.log
    fields:
      app: shipping-app
      instance: ${HOSTNAME}
    fields_under_root: false

output.logstash:
  hosts: ["vector:5044"]

logging.to_files: false
logging.to_stderr: true
