---
aws_region: us-east-1
aws_vpc_id: vpc-0a8da295096dc54ca
aws_subnet_id: subnet-028f15e6e769e14a4
aws_security_group_id: sg-0e6f6dfc3c8bf4c69
aws_instance_id: i-06b959456304d44e1

vector_system_user: vector
vector_system_group: vector

vector_data_root: /var/log/vector

vector_version: "0.43.0"
vector_target: "x86_64-unknown-linux-musl"
vector_listen_port: 5044

node_exporter_version: "1.8.2"
node_exporter_arch: "amd64"
node_exporter_port: 9100
textfile_collector_dir: /var/lib/node_exporter/textfile_collector
metrics_interval_seconds: 900

log_archive_retention_days: 30

os_tuning_vm_swappiness: 1
os_tuning_vm_dirty_background_ratio: 5
os_tuning_vm_dirty_ratio: 10
os_tuning_fs_file_max: 2097152
os_tuning_net_somaxconn: 4096
os_tuning_net_tcp_max_syn_backlog: 4096
os_tuning_net_netdev_max_backlog: 5000
os_tuning_net_rmem_max: 16777216
os_tuning_net_wmem_max: 16777216

vector_limit_nofile: 1048576
vector_connection_limit: 4096
vector_receive_buffer_bytes: 262144
vector_sink_buffer_max_size: 536870912
