sources:
  filebeat:
    type: logstash
    address: 0.0.0.0:5044

sinks:
  logs_por_app:
    type: file
    inputs:
      - filebeat
    path: "/mnt/logs/{{ fields.app }}/%Y-%m-%d/{{ host.name }}/{{ fields.app }}.log"
    encoding:
      codec: text
    healthcheck:
      enabled: true
