---
- name: Provisionar concentrador de logs (Vector)
  hosts: vector
  become: true
  gather_facts: true
  roles:
    - common
    - vector
    - node_exporter
    - textfile_collector
    - logrotate
    - archive_logs
